#pragma once

#ifdef _DEBUG
#pragma comment (lib, "PhysX_64.lib") 
#pragma comment (lib, "PhysXExtensions_static_64.lib") 
#pragma comment (lib, "PhysXPvdSDK_static_64.lib") 
//#pragma comment (lib, "PhysXVehicle_static_64.lib") 
#pragma comment (lib, "PhysXCharacterKinematic_static_64.lib") 
#pragma comment (lib, "PhysXCooking_64.lib") 
#pragma comment (lib, "PhysXCommon_64.lib") 
#pragma comment (lib, "SnippetUtils_static_64.lib") 
#pragma comment (lib, "SnippetRender_static_64.lib") 
#pragma comment (lib, "PhysXFoundation_64.lib") 
#else
#pragma comment (lib, "PhysX_64_Release.lib") 
#pragma comment (lib, "PhysXExtensions_static_64_Release.lib") 
#pragma comment (lib, "PhysXPvdSDK_static_64_Release.lib") 
//#pragma comment (lib, "PhysXVehicle_static_64_Release.lib") 
#pragma comment (lib, "PhysXCharacterKinematic_static_64_Release.lib") 
#pragma comment (lib, "PhysXCooking_64_Release.lib") 
#pragma comment (lib, "PhysXCommon_64_Release.lib") 
#pragma comment (lib, "SnippetUtils_static_64_Release.lib") 
#pragma comment (lib, "SnippetRender_static_64_Release.lib") 
#pragma comment (lib, "PhysXFoundation_64_Release.lib") 
#endif 
#pragma comment (lib, "kernel32.lib") 
#pragma comment (lib, "user32.lib") 
#pragma comment (lib, "gdi32.lib") 
#pragma comment (lib, "winspool.lib") 
#pragma comment (lib, "shell32.lib") 
#pragma comment (lib, "ole32.lib") 
#pragma comment (lib, "oleaut32.lib") 
#pragma comment (lib, "uuid.lib")
#pragma comment (lib, "comdlg32.lib") 
#pragma comment (lib, "advapi32.lib")